### ISSUE TITLE
محصول غیر ایرانی

### ISSUE THREAD

**Issue by Ezky-2** [mohali4/redshoes#1]
وقتی رو ویندوز اجراش می کنم ارور می ده روی گوشی هم همینطور این چه برنامه آشغالی داری واقعا جمعش کن این چرت هارو تازه اینگیلیسی هم نوشتی هیچی هم نمی‌فهمی حالا اینا خوبه رفتم کد هاشو بخونم ببینم مشکلش چیه اونا هم اینگیلیسی بود یعنی یه ذره غیرت تو جوان ایرانی نمونده

**Comment by mohali4** [comment]
داداش این اپ فقط روی لینوکس کار میکنه و ایرانی جماعت هم لینوکس ندارن کلا کاریش نمیشه کرد

**Comment by meshya** [comment]
اوهوم
