### ISSUE TITLE
محصول غیر ایرانی

### ISSUE THREAD

**Issue by mr-rezaaa** [mohali4/redshoes#2]
خاک توسرت اصلا ن بالا نمیاد بعد میگه اینتر نت شما ضعیف است بعد میگه برایه لینوکس است کاشکی دیسلایک داشت من راضی نیستم 😵‍💫😵‍💫😵‍💫😵‍💫😵‍💫🤬🤬💩☠️💀💩💩💩💩💩💩💩💩💩💩💩💘دماغ دراز ...............................👃👃👃👃👃👃👃بویه سوختنی هم میده با اون انیمه هاش  国はオビサカーو...............ウェブ

توف توریا 🫢🫢🫢😋😋😋😶‍🌫️😶‍🌫️😶‍🌫️🫥🫥🫥🥸🥸🥸😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😖😖😖🤬🤬🤬😈👻😈😈👻😰😯🥴😷😮‍💨😑🫢👣👣👣👣👣👣👣👣👣👣👣👣

**Comment by meshya** [comment]
باشه
